version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
          - cache-v2-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: cache-v2-{{ checksum "yarn.lock" }}
      - run: yarn lint
      - run: yarn jest --coverage && cat ./coverage/lcov.info | yarn coveralls

